# Exported from Render on 2024-11-28T18:40:14Z
services:
- type: web
  name: vehical_record_web_service
  runtime: docker
  repo: https://github.com/adil-26/vehical_record
  plan: free
  envVars:
  - key: DB_PASSWORD
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_NAME
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_HOST
    sync: false
  region: singapore
  dockerContext: .
  dockerfilePath: Dockerfile
  rootDir: vehiclerecordsystem/
version: "1"
